controller_communication_node:
  ros__parameters:

    controller_ip: "192.168.0.2"
    
    controller_port: 23

    joints_names:
      - "J1"
      - "J2"
      - "J3"
      - "J4"

    # [enc_min, enc_max, range_min(rad), range_max(rad)]
    joints_ranges:
      # J1
      - -385506.0
      -  380555.0
      - -2.3038346
      -  2.3038346

      # J2
      - -437972.0
      -  439198.0
      - -2.6179939
      -  2.6179939

      # J3
      - -1707.0
      -  250000.0
      -  0.0
      - -0.150

      # J4
      - -245760.0
      -  245760.0
      - -6.2831853
      -  6.2831853